"use client";

import React from 'react';
import MuseumLayout from '@/components/Layout/MuseumLayout';
import { motion } from 'framer-motion';
import { LibraryBig, BrainCircuit, Mic } from 'lucide-react';

export default function AboutPage() {
    return (
        <MuseumLayout>
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-3xl mx-auto text-center"
            >
                <h1 className="text-5xl font-serif font-bold text-museum-text mb-8">About the Museum</h1>
                <p className="text-xl text-gray-300 mb-12 leading-relaxed">
                    The <span className="text-museum-gold font-serif">NotebookLM Originals Museum</span> is an experimental platform dedicated to curating and preserving educational audio content generated by advanced artificial intelligence.
                </p>

                <div className="grid md:grid-cols-3 gap-8 mb-16">
                    <div className="p-6 bg-museum-card rounded-xl border border-white/5">
                        <LibraryBig size={40} className="text-museum-gold mx-auto mb-4" />
                        <h3 className="font-serif text-lg text-white mb-2">Curated Content</h3>
                        <p className="text-sm text-gray-400">Hand-selected dialogues on Art History, Architecture, and Design.</p>
                    </div>
                    <div className="p-6 bg-museum-card rounded-xl border border-white/5">
                        <BrainCircuit size={40} className="text-museum-gold mx-auto mb-4" />
                        <h3 className="font-serif text-lg text-white mb-2">AI Generated</h3>
                        <p className="text-sm text-gray-400">Powered by Google's NotebookLM, synthesizing complex sources into engaging audio.</p>
                    </div>
                    <div className="p-6 bg-museum-card rounded-xl border border-white/5">
                        <Mic size={40} className="text-museum-gold mx-auto mb-4" />
                        <h3 className="font-serif text-lg text-white mb-2">Immersive Audio</h3>
                        <p className="text-sm text-gray-400">High-fidelity audio playback designed for deep listening and learning.</p>
                    </div>
                </div>

                <div className="prose prose-invert max-w-none text-left bg-museum-card/50 p-8 rounded-2xl border border-white/5">
                    <h2 className="font-serif text-2xl text-museum-text mb-4">Our Mission</h2>
                    <p className="text-gray-300 mb-4">
                        We believe that the future of education lies at the intersection of human curation and artificial intelligence. This platform serves as a gallery for these new forms of knowledge transmission.
                    </p>
                    <p className="text-gray-300">
                        Initially restricted to students and researchers, the collection will grow to encompass a wider range of humanities subjects, always with a focus on depth, accuracy, and aesthetic presentation.
                    </p>
                </div>
            </motion.div>
        </MuseumLayout>
    );
}
